# Make sure to check the documentation at http://goreleaser.com
project_name: AuroraBoot
builds:
  - ldflags:
      - -w -s -X main.version={{.Env.BINARY_VERSION}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: '{{ .ProjectName }}'
