package cmd

import (
	"github.com/kairos-io/AuroraBoot/pkg/secureboot"
	"github.com/kairos-io/kairos-sdk/types/logger"
	"github.com/urfave/cli/v2"
)

const (
	skipMicrosoftCertsFlag = "skip-microsoft-certs-I-KNOW-WHAT-IM-DOING"
	customCertDirFlag      = "custom-cert-dir"
)

var GenKeyCmd = cli.Command{
	Name:      "genkey",
	Aliases:   []string{"gk"},
	Usage:     "Generate secureboot keys under the uuid generated by NAME",
	ArgsUsage: "<name>",
	Flags: []cli.Flag{
		&cli.StringFlag{
			Name:    "output",
			Aliases: []string{"o"},
			Value:   "keys/",
			Usage:   "Output directory for the keys",
		},
		&cli.StringFlag{
			Name:    "expiration-in-days",
			Aliases: []string{"e"},
			Value:   "365",
			Usage:   "In how many days from today should the certificates expire",
		},
		&cli.BoolFlag{
			Name:  skipMicrosoftCertsFlag,
			Value: false,
			Usage: "When set to true, microsoft certs are not included in the KEK and db files. THIS COULD BRICK YOUR SYSTEM! (https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#Enrolling_Option_ROM_digests). Only use this if you are sure your hardware doesn't need the microsoft certs!",
		},
		&cli.StringFlag{
			Name:  customCertDirFlag,
			Usage: "Path to a directory containing custom certificates to enroll",
		},
	},
	Action: func(ctx *cli.Context) error {
		log := logger.NewKairosLogger("auroraboot", "debug", false)
		return secureboot.GenerateKeySet(secureboot.Options{
			Name:               ctx.Args().Get(0),
			OutputDir:          ctx.String("output"),
			ExpirationInDays:   ctx.String("expiration-in-days"),
			SkipMicrosoftCerts: ctx.Bool(skipMicrosoftCertsFlag),
			CustomCertDir:      ctx.String(customCertDirFlag),
			Logger:             &log,
		})
	},
}
