package isoserve

import (
	"fmt"
	"net"
	"net/url"
	"strings"
)

// allowedSchemes is the scheme allowlist for operator-supplied media URLs. http
// and https cover the common BMC virtual-media case; NFS/CIFS are intentionally
// excluded here (they have their own host/share semantics and are not used by
// AuroraBoot's serve helper).
var allowedSchemes = map[string]bool{
	"http":  true,
	"https": true,
}

// ValidateMediaURL applies SSRF guards to an operator-supplied URL (the CLI
// --image-url or the BMC endpoint). It enforces the scheme allowlist and rejects
// hosts that resolve to the always-deny set (loopback, link-local/metadata,
// unspecified). It does NOT blanket-block RFC1918/private ranges: the legitimate
// serve host is usually on a private BMC management network.
//
// The host is resolved once and every resolved IP is checked. URLs generated by
// the serve helper itself are trusted by construction and need not be passed
// through this.
func ValidateMediaURL(raw string) error {
	u, err := url.Parse(strings.TrimSpace(raw))
	if err != nil {
		return fmt.Errorf("validating media URL: %w", err)
	}

	scheme := strings.ToLower(u.Scheme)
	if !allowedSchemes[scheme] {
		return fmt.Errorf("validating media URL: scheme %q is not allowed (use http or https)", u.Scheme)
	}

	host := u.Hostname()
	if host == "" {
		return fmt.Errorf("validating media URL: missing host")
	}

	// A literal IP is checked directly; a hostname is resolved and every answer
	// is checked (resolve-and-validate once).
	if ip := net.ParseIP(host); ip != nil {
		if blocked, reason := isBlockedIP(ip); blocked {
			return fmt.Errorf("validating media URL: host %s is not allowed (%s)", host, reason)
		}
		return nil
	}

	ips, err := net.LookupIP(host)
	if err != nil {
		return fmt.Errorf("validating media URL: resolving host %q: %w", host, err)
	}
	if len(ips) == 0 {
		return fmt.Errorf("validating media URL: host %q resolved to no addresses", host)
	}
	for _, ip := range ips {
		if blocked, reason := isBlockedIP(ip); blocked {
			return fmt.Errorf("validating media URL: host %q resolves to %s, which is not allowed (%s)", host, ip, reason)
		}
	}
	return nil
}

// isBlockedIP reports whether ip is in the always-deny set: loopback,
// link-local (incl. the 169.254.169.254 cloud-metadata address and IPv6
// fe80::/10), or unspecified (0.0.0.0 / ::). RFC1918/private ranges are
// deliberately allowed.
func isBlockedIP(ip net.IP) (bool, string) {
	switch {
	case ip.IsLoopback():
		return true, "loopback"
	case ip.IsUnspecified():
		return true, "unspecified address"
	case ip.IsLinkLocalUnicast():
		return true, "link-local (includes cloud metadata)"
	case ip.IsLinkLocalMulticast():
		return true, "link-local multicast"
	}
	return false, ""
}
