import { describe, expect, it } from "vitest";

import { renderHadronMiddleContent } from "./hadronContent";

describe("renderHadronMiddleContent", () => {
  it("normalizes a symlinked firmware destination and appends content in caller order", () => {
    expect(
      renderHadronMiddleContent(
        ["firmware:first", "firmware:second"],
        ["layer:first", "layer:second"],
        "RUN echo ready",
      ),
    ).toBe(
      "# Generated by AuroraBoot Hadron composer — do not edit\n" +
        "RUN if [ -L /usr/local/lib/firmware ]; then \\\n" +
        "        rm /usr/local/lib/firmware && mkdir -p /usr/local/lib/firmware; \\\n" +
        "    fi\n" +
        "COPY --from=firmware:first / /\n" +
        "COPY --from=firmware:second / /\n" +
        "COPY --from=layer:first / /\n" +
        "COPY --from=layer:second / /\n" +
        "RUN echo ready\n",
    );
  });

  it("emits only the compatibility guard when inputs are empty", () => {
    expect(renderHadronMiddleContent([], [], "")).toBe(
      "# Generated by AuroraBoot Hadron composer — do not edit\n" +
        "RUN if [ -L /usr/local/lib/firmware ]; then \\\n" +
        "        rm /usr/local/lib/firmware && mkdir -p /usr/local/lib/firmware; \\\n" +
        "    fi\n",
    );
  });
});
