import { describe, expect, it } from "vitest";

import { renderHadronMiddleContent } from "./hadronContent";

describe("renderHadronMiddleContent", () => {
  it("preserves the base layout and appends content in caller order", () => {
    expect(
      renderHadronMiddleContent(
        ["firmware:first", "firmware:second"],
        ["layer:first", "layer:second"],
        "RUN echo ready",
      ),
    ).toBe(
      "# Generated by AuroraBoot Hadron composer — do not edit\n" +
        "COPY --from=firmware:first / /\n" +
        "COPY --from=firmware:second / /\n" +
        "COPY --from=layer:first / /\n" +
        "COPY --from=layer:second / /\n" +
        "RUN echo ready\n",
    );
  });
});
