// Produces the Hadron "middle content": one COPY per firmware in spec order,
// one COPY per layer in spec order, and the user's extra content appended
// verbatim. The base image layout must stay intact: /usr/local is persistent
// state and Hadron uses a merged-/usr filesystem.
//
// The FROM line is not emitted here. Both backends receive HadronBase as a
// separate structured field: the local backend prepends "FROM ${HadronBase}"
// before feeding buildah, and the operator injects it via BuildOptions.
export function renderHadronMiddleContent(
  firmware: string[],
  layers: string[],
  extra: string,
): string {
  let out = "# Generated by AuroraBoot Hadron composer — do not edit\n";
  for (const ref of firmware) out += `COPY --from=${ref} / /\n`;
  for (const ref of layers) out += `COPY --from=${ref} / /\n`;
  const trimmed = extra.trim();
  if (trimmed) out += trimmed + (trimmed.endsWith("\n") ? "" : "\n");
  return out;
}
