// Produces the Hadron "middle content": a compatibility guard for older bases,
// one COPY per firmware in spec order, one COPY per layer in spec order, and
// the user's extra content appended verbatim. Older Hadron bases expose the
// firmware destination as a symlink, which BuildKit cannot copy a directory
// over. Replace only that symlink and otherwise leave the base layout intact.
//
// The FROM line is not emitted here. Both backends receive HadronBase as a
// separate structured field: the local backend prepends "FROM ${HadronBase}"
// before feeding buildah, and the operator injects it via BuildOptions.
export function renderHadronMiddleContent(
  firmware: string[],
  layers: string[],
  extra: string,
): string {
  let out = "# Generated by AuroraBoot Hadron composer — do not edit\n";
  out +=
    "RUN if [ -L /usr/local/lib/firmware ]; then \\\n" +
    "        rm /usr/local/lib/firmware && mkdir -p /usr/local/lib/firmware; \\\n" +
    "    fi\n";
  for (const ref of firmware) out += `COPY --from=${ref} / /\n`;
  for (const ref of layers) out += `COPY --from=${ref} / /\n`;
  const trimmed = extra.trim();
  if (trimmed) out += trimmed + "\n";
  return out;
}
