{{- include "auroraboot.requireHost" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auroraboot.registrationSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auroraboot.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ include "auroraboot.registrationToken" . | b64enc | quote }}
