apiVersion: v2
name: auroraboot
description: AuroraBoot web UI wired to the kairos-operator as its build backend.
type: application
version: 0.27.0
appVersion: "v0.27.0"
home: https://kairos.io
sources:
  - https://github.com/kairos-io/AuroraBoot
maintainers:
  - name: kairos-io
    url: https://github.com/kairos-io
keywords:
  - kairos
  - auroraboot
  - netboot
  - immutable-os
