package hadron

import (
	"strings"
	"testing"
)

// fwLayoutFix is the exact RUN line RenderDockerfile emits before every
// firmware/layer copy so historic hadron tags (v0.5.0 and earlier) end up with
// a real directory at /usr/local/lib/firmware and a symlink /lib/firmware ->
// it. Runtime-detected, so it's a no-op on post-fix hadron images.
const fwLayoutFix = "RUN if [ -L /usr/local/lib/firmware ] || [ ! -d /usr/local/lib/firmware ]; then \\\n" +
	"        rm -rf /usr/local/lib/firmware /lib/firmware && \\\n" +
	"        mkdir -p /usr/local/lib/firmware && \\\n" +
	"        ln -s /usr/local/lib/firmware /lib/firmware; \\\n" +
	"    fi && \\\n" +
	"    if [ -L /usr/sbin ]; then \\\n" +
	"        rm /usr/sbin && mkdir /usr/sbin; \\\n" +
	"    fi\n"

func TestRenderDockerfile(t *testing.T) {
	cases := []struct {
		name string
		spec Spec
		want string
	}{
		{
			name: "base only still emits the firmware-layout rewrite so layer-only builds are sysext-compatible",
			spec: Spec{BaseImage: "ghcr.io/kairos-io/hadron:main"},
			want: "# Generated by AuroraBoot — do not edit\n" +
				"FROM ghcr.io/kairos-io/hadron:main\n" +
				fwLayoutFix,
		},
		{
			name: "firmware only preserves order and strips the symlink first",
			spec: Spec{
				BaseImage: "ghcr.io/kairos-io/hadron:v1",
				Firmware: []string{
					"ghcr.io/kairos-io/hadron-firmware/linux-firmware-amdgpu:20260622",
					"ghcr.io/kairos-io/hadron-firmware/linux-firmware-rtw88:20260622",
				},
			},
			want: "# Generated by AuroraBoot — do not edit\n" +
				"FROM ghcr.io/kairos-io/hadron:v1\n" +
				fwLayoutFix +
				"COPY --from=ghcr.io/kairos-io/hadron-firmware/linux-firmware-amdgpu:20260622 / /\n" +
				"COPY --from=ghcr.io/kairos-io/hadron-firmware/linux-firmware-rtw88:20260622 / /\n",
		},
		{
			name: "layers only preserves order",
			spec: Spec{
				BaseImage: "ghcr.io/kairos-io/hadron:v1",
				Layers: []string{
					"ghcr.io/kairos-io/git:latest",
					"ghcr.io/kairos-io/gpg:latest",
				},
			},
			want: "# Generated by AuroraBoot — do not edit\n" +
				"FROM ghcr.io/kairos-io/hadron:v1\n" +
				fwLayoutFix +
				"COPY --from=ghcr.io/kairos-io/git:latest / /\n" +
				"COPY --from=ghcr.io/kairos-io/gpg:latest / /\n",
		},
		{
			name: "firmware before layers, both present",
			spec: Spec{
				BaseImage: "ghcr.io/kairos-io/hadron:v1",
				Firmware:  []string{"ghcr.io/kairos-io/hadron-firmware/linux-firmware-amdgpu:20260622"},
				Layers:    []string{"ghcr.io/kairos-io/git:latest"},
			},
			want: "# Generated by AuroraBoot — do not edit\n" +
				"FROM ghcr.io/kairos-io/hadron:v1\n" +
				fwLayoutFix +
				"COPY --from=ghcr.io/kairos-io/hadron-firmware/linux-firmware-amdgpu:20260622 / /\n" +
				"COPY --from=ghcr.io/kairos-io/git:latest / /\n",
		},
		{
			name: "extra dockerfile appended verbatim with trailing newline",
			spec: Spec{
				BaseImage:       "ghcr.io/kairos-io/hadron:v1",
				ExtraDockerfile: "RUN echo hello > /etc/motd",
			},
			want: "# Generated by AuroraBoot — do not edit\n" +
				"FROM ghcr.io/kairos-io/hadron:v1\n" +
				fwLayoutFix +
				"RUN echo hello > /etc/motd\n",
		},
		{
			name: "extra dockerfile trimmed and normalized",
			spec: Spec{
				BaseImage:       "ghcr.io/kairos-io/hadron:v1",
				ExtraDockerfile: "\n\n   RUN echo hi\n\n",
			},
			want: "# Generated by AuroraBoot — do not edit\n" +
				"FROM ghcr.io/kairos-io/hadron:v1\n" +
				fwLayoutFix +
				"RUN echo hi\n",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := RenderDockerfile(tc.spec)
			if got != tc.want {
				t.Fatalf("dockerfile mismatch:\n--- want ---\n%s\n--- got ---\n%s", tc.want, got)
			}
		})
	}
}

func TestSpecValidate(t *testing.T) {
	cases := []struct {
		name    string
		spec    Spec
		wantErr string
	}{
		{
			name:    "empty base image",
			spec:    Spec{Push: true, OutputRef: "r/x:v"},
			wantErr: "baseImage is required",
		},
		{
			name:    "base image with shell metachar",
			spec:    Spec{BaseImage: "hadron; rm -rf /", Push: true, OutputRef: "r/x:v"},
			wantErr: "baseImage",
		},
		{
			name: "firmware ref with shell metachar",
			spec: Spec{
				BaseImage: "ghcr.io/kairos-io/hadron:main",
				Firmware:  []string{"ghcr.io/x`whoami`:latest"},
				Push:      true, OutputRef: "r/x:v",
			},
			wantErr: "firmware[0]",
		},
		{
			name: "layer ref with shell metachar",
			spec: Spec{
				BaseImage: "ghcr.io/kairos-io/hadron:main",
				Layers:    []string{"ghcr.io/x$(whoami):latest"},
				Push:      true, OutputRef: "r/x:v",
			},
			wantErr: "layers[0]",
		},
		{
			name: "unsupported platform",
			spec: Spec{
				BaseImage: "ghcr.io/kairos-io/hadron:main",
				Platforms: []string{"linux/riscv64"},
				Push:      true, OutputRef: "r/x:v",
			},
			wantErr: "platform",
		},
		{
			name: "no output destination",
			spec: Spec{
				BaseImage: "ghcr.io/kairos-io/hadron:main",
			},
			wantErr: "push or produceTarball",
		},
		{
			name: "missing output ref",
			spec: Spec{
				BaseImage:      "ghcr.io/kairos-io/hadron:main",
				ProduceTarball: true,
			},
			wantErr: "outputRef is required",
		},
		{
			name: "output ref with shell metachar",
			spec: Spec{
				BaseImage:      "ghcr.io/kairos-io/hadron:main",
				ProduceTarball: true,
				OutputRef:      "r/x;boom",
			},
			wantErr: "outputRef",
		},
		{
			name: "valid multi-arch tarball spec",
			spec: Spec{
				BaseImage:      "ghcr.io/kairos-io/hadron:main",
				Firmware:       []string{"ghcr.io/kairos-io/hadron-firmware/linux-firmware-amdgpu:20260622"},
				Layers:         []string{"ghcr.io/kairos-io/git:latest"},
				Platforms:      []string{"linux/amd64", "linux/arm64"},
				ProduceTarball: true,
				OutputRef:      "example.com/team/os:v1",
			},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := tc.spec.Validate()
			if tc.wantErr == "" {
				if err != nil {
					t.Fatalf("expected valid spec, got %v", err)
				}
				return
			}
			if err == nil {
				t.Fatalf("expected error containing %q, got nil", tc.wantErr)
			}
			if !strings.Contains(err.Error(), tc.wantErr) {
				t.Fatalf("expected error containing %q, got %v", tc.wantErr, err)
			}
		})
	}
}

func TestPlatformsOrDefault(t *testing.T) {
	s := Spec{}
	if got := s.PlatformsOrDefault(); len(got) != 1 || got[0] != "linux/amd64" {
		t.Fatalf("expected [linux/amd64], got %v", got)
	}
	s = Spec{Platforms: []string{"linux/arm64"}}
	if got := s.PlatformsOrDefault(); len(got) != 1 || got[0] != "linux/arm64" {
		t.Fatalf("expected [linux/arm64], got %v", got)
	}
}
