package hadron

import (
	"strings"
)

// RenderDockerfile produces the Dockerfile text buildx consumes for this spec.
// Layout is deterministic: FROM the base, then one COPY per firmware image (in
// spec order), then one COPY per software layer (in spec order), then the
// user-supplied ExtraDockerfile appended verbatim.
//
// COPY order matches user intent because later COPY lines overwrite earlier
// ones on file conflicts — sorting would silently change the resulting image
// when two layers ship the same path.
//
// The spec must have been Validate()'d before this is called; the renderer
// does not re-check for shell metacharacters.
func RenderDockerfile(s Spec) string {
	var b strings.Builder
	b.WriteString("# Generated by AuroraBoot — do not edit\n")
	b.WriteString("FROM ")
	b.WriteString(s.BaseImage)
	b.WriteString("\n")
	// Normalize the base image's directory layout so incoming firmware and
	// layer COPYs never trip buildkit's "cannot copy to non-directory" error.
	// Two historic quirks we've seen:
	//
	//   /usr/local/lib/firmware: hadron v0.5.0 and earlier shipped this as a
	//     symlink to /lib/firmware; sysext + persistent-overlay expect a real
	//     directory here, with /lib/firmware pointing at it instead.
	//
	//   /usr/sbin: hadron v0.4.0 shipped this as a symlink to bin (collapsed
	//     sbin into bin). Layer images that ship real /usr/sbin/* files —
	//     e.g. hadron-layers/gpg — then fail to overlay.
	//
	// Both are runtime-detected so post-fix bases short-circuit into a
	// no-op. Emitted on every build (not gated on Firmware/Layers > 0) so
	// even a bare `FROM hadron` produces a consistent layout.
	b.WriteString("RUN if [ -L /usr/local/lib/firmware ] || [ ! -d /usr/local/lib/firmware ]; then \\\n" +
		"        rm -rf /usr/local/lib/firmware /lib/firmware && \\\n" +
		"        mkdir -p /usr/local/lib/firmware && \\\n" +
		"        ln -s /usr/local/lib/firmware /lib/firmware; \\\n" +
		"    fi && \\\n" +
		"    if [ -L /usr/sbin ]; then \\\n" +
		"        rm /usr/sbin && mkdir /usr/sbin; \\\n" +
		"    fi\n")
	for _, ref := range s.Firmware {
		b.WriteString("COPY --from=")
		b.WriteString(ref)
		b.WriteString(" / /\n")
	}
	for _, ref := range s.Layers {
		b.WriteString("COPY --from=")
		b.WriteString(ref)
		b.WriteString(" / /\n")
	}
	extra := strings.TrimSpace(s.ExtraDockerfile)
	if extra != "" {
		b.WriteString(extra)
		if !strings.HasSuffix(extra, "\n") {
			b.WriteString("\n")
		}
	}
	return b.String()
}
