package docs

import _ "embed"

// SwaggerYAML is the generated OpenAPI document in YAML form. It lives
// alongside the swag-generated docs.go (which only exposes the JSON
// form) so callers can prefer whichever representation they need. The
// server uses this to serve `/api/v1/openapi.yaml`.
//
// Regenerated by `make openapi` whenever handler annotations change.
//
//go:embed swagger.yaml
var SwaggerYAML []byte
