---
name: 'Release images'

on:
  push:
    tags:
      - '*'

concurrency:
  group: ci-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: false # we never want to cancel a running job on release
jobs:
  build-linux-amd64:
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          # https://docs.redhat.com/en/documentation/red_hat_quay/3.4/html/use_red_hat_quay/working_with_tags#tag-expiration
          labels: |
            quay.expires-after=6h
          build-args: |
            VERSION=${{ github.ref_name }}
          provenance: false
          platforms: linux/amd64
          push: true
          tags: quay.io/kairos/ci-temp-images:auroraboot-${{ github.sha }}-amd64
  build-linux-arm64:
    runs-on: 'ubuntu-24.04-arm'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          # https://docs.redhat.com/en/documentation/red_hat_quay/3.4/html/use_red_hat_quay/working_with_tags#tag-expiration
          labels: |
            quay.expires-after=6h
          build-args: |
            VERSION=${{ github.ref_name }}
          provenance: false
          platforms: linux/arm64
          push: true
          tags: quay.io/kairos/ci-temp-images:auroraboot-${{ github.sha }}-arm64
  build:
    needs:
      - build-linux-amd64
      - build-linux-arm64
    runs-on: ubuntu-24.04
    steps:
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: quay.io/kairos/auroraboot
      - uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          sources: |
            quay.io/kairos/ci-temp-images:auroraboot-${{ github.sha }}-amd64
            quay.io/kairos/ci-temp-images:auroraboot-${{ github.sha }}-arm64
